version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: nftstore_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nftstore
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
    driver: local
